#!/bin/bash

### [INTRO] ###
echo "Welcome to MyHarem (c)2003-2020 By Claudio Nanni"
echo " "

### [SET CONFIGURATION] ###
source /etc/myharem.conf
export basedir
export dbuser
export instances=$basedir/instances
export local=$basedir/local
export remote=$basedir/remote
export erased=$basedir/erased
export logdir=$basedir/logs


### [SETUP IF FIRST INVOCATION USING 'basedir'] ###
# Create structure in case it is the first time. Add checks later to create only if.
if [ -d "$basedir" ];
then
  echo "Working Basedir in: $basedir...."
  echo ""
else
  echo "It seems this Base dir is a new one. Creating full structure under $basedir..."
  mkdir -p $basedir
  mkdir -p $instances
  mkdir -p $local
  mkdir -p $remote
  mkdir -p $erased
  mkdir -p $logdir
  echo "Changing ownership of directory tree to: $dbuser"
  chown -R $dbuser:$dbuser $basedir
  echo " "
fi

### [CHECK PARAMETERS] ###
if [ "$#" -eq 0 ]
then
  echo "MyHarem - available commands:"
  echo "============================="
  ls -1 $0-* | awk -F"-" '{print $1" "$2}'
  exit
fi

### [LAUNCH COMMAND WITH PARAMETERS. NOW ONLY MAX THREE CONTEMPLATED] ###
mh-$1 $2 $3 $4

exit

### [CURRENT AVAILABLE COMMANDS] ###

:cmd:mh-cli:
:dsc:connect with mysql client to an instance

:cmd:mh-scli:
:dsc:connect with mysql client to an instance using root via socket

:cmd:mh-deploy:
:dsc:deploy an instance using the specified id which will also be used as server-id, tcp port, socket
:mh-show:

:cmd:mh-service:
:dsc:start/stop/install an instance

:cmd:mh-status:
:dsc:show the current general status

:cmd:mh-erase:
:dsc:eliminate an instance deployement from disk including all data

:cmd:mh-tarballs:
:dsc:retrieve the binary tarballs urls from a remote fixed webpage (updated manually). It is a facility to help get at least latest major releases.





