#!/usr/bin/bash
echo " "
if [ "$1" == help ]
then
  echo "MyHarem tarballs - updates the list of remotely available tarballs"
  echo "============================="
  echo "Usage: mh tarballs"
  echo " "
  exit
fi
echo " "
echo "MyHarem tarballs - updates the list of remotely available tarballs"
echo " "
echo "Getting fresh list of tarballs... "
echo " "
wget http://myharem.mysql.name/wp-content/uploads/2014/02/mh-tarballs.txt -O /var/opt/myharem/remote/list
#more /var/opt/myharem/remote/list
echo "Updated list is in $basedir/remote/list, use: mh show remote  for more information"
